#ifndef DUSTY_SCANNER_H
#define DUSTY_SCANNER_H

struct Scanner {
    const char *source;
    int cursor;
    int line;
    int column;
};

enum TokenType {
    TOKEN_EOF = 0,
    TOKEN_INT, TOKEN_FLOAT, TOKEN_DOUBLE, TOKEN_CHAR, TOKEN_STRING, TOKEN_IF,
    TOKEN_ELSE, TOKEN_FUNCTION, TOKEN_FOR, TOKEN_WHILE, TOKEN_RETURN, TOKEN_BREAK,

    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_NOT, TOKEN_NOT_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_LESS_LESS, TOKEN_GREATER, TOKEN_GREATER_EQUAL,
    TOKEN_GREATER_GREATER, TOKEN_COMMA, TOKEN_MUL, TOKEN_MUL_EQUAL, TOKEN_DIV, TOKEN_DIV_EQUAL,
    TOKEN_PLUS, TOKEN_PLUS_EQUAL, TOKEN_PLUS_PLUS, TOKEN_MINUS, TOKEN_MINUS_EQUAL, TOKEN_MINUS_MINUS,
    TOKEN_MOD, TOKEN_MOD_EQUAL, TOKEN_AND, TOKEN_AND_EQUAL, TOKEN_AND_AND, TOKEN_OR, TOKEN_OR_EQUAL, 
    TOKEN_OR_OR, TOKEN_COLON, TOKEN_COLON_COLON, TOKEN_SEMICOLON, TOKEN_EQUAL, TOKEN_EQUAL_EQUAL, 
    TOKEN_LBRACKET, TOKEN_RBRACKET, TOKEN_CARET, TOKEN_CARET_EQUAL,

    TOKEN_NUMERIC_CONSTANT, TOKEN_STRING_CONSTANT, TOKEN_IDENT,

    TOKEN_ERROR
};

struct Token {
    enum TokenType type;
    int start;
    int length;
    int line;
    int col;
    const char *lexeme;
};

struct TokenList {
    struct Token *tokens;
    int count;
    int capacity;
};

int tokenize(const char *source, struct TokenList *tokens);

#endif // DUSTY_SCANNER_H
